name: Validate to Production Environment

on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]
    paths:
      - 'force-app/**'

jobs:

  validate-to-prod:
    uses: ./.github/workflows/action-validate.yml
    with:
      environment: devss
    secrets: inherit

    permissions:
      actions: read 
      security-events: write 
      contents: read
      issues: write
      pull-requests: write