name: Deploy to Production Environment

on:
  push:
    branches: [ main ]
    paths:
      - 'force-app/**'

jobs:
  
  deploy-to-prod:
    uses: ./.github/workflows/action-deploy.yml
    with:
      environment: devss
    secrets: inherit

    permissions:
      actions: read 
      security-events: write 
      contents: read
      issues: write