name: Run Anonymous Apex

on:
  workflow_dispatch:
    inputs:
      apex_script_path:
        description: "Path to Anonymous Apex Script (e.g., scripts/scripts-ci/script.apex)"
        required: true
        type: string
      environment:
        description: "Salesforce Environment"
        required: true
        type: choice
        options:
          - prod
          - uat
          - devss

jobs:

  deploy:
    runs-on: ubuntu-latest
    name: Run Anonymous Apex in ${{ inputs.environment }}
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Salesforce Environment
        uses: ./.github/actions/setup-salesforce

      - name: 'Authenticate to Salesforce'
        run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
          sf org login jwt \
            --username ${{ secrets.DEPLOYMENT_USER }} \
            --jwt-key-file server.key \
            --client-id ${{ secrets.CONSUMER_KEY }} \
            --instance-url ${{ vars.INSTANCE_URL }} \
            --set-default \
            --set-default-dev-hub

      - name: 'Check if Apex Script Exists'
        run: |
          if [ ! -f "${{ inputs.apex_script_path }}" ]; then
            echo "ERROR: Apex script not found at ${{ inputs.apex_script_path }}";
            exit 1;
          fi

      - name: 'Copy Script to Temporary File and Execute'
        run: |
          cp "${{ inputs.apex_script_path }}" temp_script.apex
          sf apex run --file temp_script.apex --target-org ${{ secrets.DEPLOYMENT_USER }}